version: "3.7"

services:
  nats:
    image: ${DOCKER_HUB}${NATS_IMAGE:-nats:2.10}
    entrypoint: nats-server
    command: --jetstream --profile 6060
  client:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DOCKER_HUB=${DOCKER_HUB}
    environment:
      - NATS_URL=nats:4222
    command:
       - /opt/nats-bench
       - -approach=${APPROACH:-multiple-filter-subjects}
       - -num-realms=${NUM_REALMS:-10000}
       - -num-consumers=${NUM_CONSUMERS:-20}
       - -num-realms-per-consumer=${NUM_REALMS_PER_CONSUMER:-50}
    depends_on:
      - nats
  pprof:
    image: ${DOCKER_HUB}alpine:3.18
    volumes:
      - type: bind
        source: ./profiles
        target: /tmp/profiles
    command: wget http://nats:6060/debug/pprof/profile -O /tmp/profiles/nats.profile
    depends_on:
      - nats
